In [1]:
# Importação das bibliotecas necessárias

import pandas as pd
import numpy as np
import glob
import math

In [2]:
# Definição da loja a ser utilizada

loja = 1
periodo = 2

In [3]:
# Leitura do arquivo de entradas-operação própria

file_1 = pd.read_csv(f"C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\nfe_entrada_oppropr.txt",sep = '\t', header=1, encoding='utf-8', encoding_errors='ignore')
file_1.head()

# Colunas a serem usadas:
# 'Chave Acesso NFe', 'Data Emissão', 'Número item', 'Código Produto ou Serviço'
# 'Código CFOP (04 Posições)', 'Quantidade Comercial', 'Valor Produto ou Serviço', 'Valor ICMS Operação'
# 'Valor ICMS Substituição Tributária','', 'Valor Base Cálculo ICMS ST Retido Operação Anterior'
# 'Descrição Produto', 'Código GTIN', 'Unidade Comercial', 'Código NCM'
# 'Código CEST', 'Documento Fiscal.Número CNPJ Emitente (char)'
# 'Número CNPJ Destinatário (char)'

,Chave Acesso NFe,Código CFOP (04 Posições),Descrição Produto,Número Item,Data Emissão,Unidade Comercial,Número CNPJ Destinatário,Número CNPJ Emitente,Código NCM,Cod UF Emitente,...,Valor ICMS,Valor ICMS Substituição Tributária,Valor ICMS Substituição Tributária Destino,Valor Total NFE do Produto,Valor Total Tributo,Valor Desconto Incondicional,Valor Desconto Condicional,Valor ICMS Substituto,Valor Frete,Valor Seguro
0,35161003129126000159550020000014241120604712,1411,Esc D Frescor 3d Piu Piu,1,02/10/2016,UN,NaN,3129126000159,96032100,SP,...,NaN,NaN,NaN,"11,9","3,13",NaN,NaN,NaN,NaN,NaN
1,35161003129126000159550020000014251120604973,1411,Removedor Esm 80ml Farmax,1,02/10/2016,UN,NaN,3129126000159,33043000,SP,...,NaN,NaN,NaN,"3,56","1,73",NaN,NaN,NaN,NaN,NaN
2,35161003129126000159550020000014261120605020,1411,Sb JeJ 90g Harmonize Erva Doce,3,02/10/2016,UN,NaN,3129126000159,34011190,SP,...,NaN,NaN,NaN,"4,11","1,41",NaN,NaN,NaN,NaN,NaN
3,35161003129126000159550020000014261120605020,1411,Sb JeJ 90g Imagine Rosa Jasm,1,02/10/2016,UN,NaN,3129126000159,34011190,SP,...,NaN,NaN,NaN,"4,11","1,41",NaN,NaN,NaN,NaN,NaN
4,35161003129126000159550020000014261120605020,1411,Sb JeJ 90g Relaxe Lavanda,2,02/10/2016,UN,NaN,3129126000159,34011190,SP,...,NaN,NaN,NaN,"2,74","0,94",NaN,NaN,NaN,NaN,NaN

In [4]:
file_1['Número CNPJ Destinatário'].unique()

array([          nan, 5.6519660e+12, 3.1291260e+12, 6.1940292e+13,
       1.8901772e+13])

In [4]:
file_1.columns

Index(['Chave Acesso NFe', 'Código CFOP (04 Posições)', 'Descrição Produto',
       'Número Item', 'Data Emissão', 'Unidade Comercial',
       'Número CNPJ Destinatário', 'Número CNPJ Emitente', 'Código NCM',
       'Cod UF Emitente', 'Cod UF Destinatário',
       'Documento Fiscal.Número CNPJ Emitente (char)',
       'Documento Fiscal Produto.Número CNPJ Emitente (char)',
       'Número CNPJ Destinatário (char)',
       'Descrição Informações Adicionais Produto (original)',
       'Descrição Informações Adicionais Produto',
       'Indicador Tipo Documento Fiscal',
       'Valor Base Cálculo ICMS ST Retido Operação Anterior', 'Código CEST',
       'Código CEST (char)', 'Código GTIN', 'Código Produto ou Serviço',
       'Valor Base Cálculo ICMS Substituição Tributária',
       'Valor Base Cálculo ICMS ST Destino', 'Quantidade Comercial',
       'Quantidade Tributável', 'Valor ICMS FCP ST Retido',
       'Valor Percentual FCP ST Retido', 'Valor Base Cálculo FCP ST Retido',
       'Valor ICMS ST Retido Operação Anterior', 'Valor Produto ou Serviço',
       'Valor ICMS', 'Valor ICMS Substituição Tributária',
       'Valor ICMS Substituição Tributária Destino',
       'Valor Total NFE do Produto', 'Valor Total Tributo',
       'Valor Desconto Incondicional', 'Valor Desconto Condicional',
       'Valor ICMS Substituto', 'Valor Frete', 'Valor Seguro'],
      dtype='object')

In [5]:
# Seleção das colunas necessárias do
# arquivo entradas-operação própria

file_1_new = file_1.copy()
file_1_new = file_1_new[['Chave Acesso NFe', 'Data Emissão', 'Número Item', 'Código Produto ou Serviço',
                    'Código CFOP (04 Posições)', 'Quantidade Comercial', 'Valor Produto ou Serviço','Valor ICMS',
                    'Valor ICMS Substituição Tributária', 'Valor Base Cálculo ICMS Substituição Tributária',
                    'Valor Base Cálculo ICMS ST Retido Operação Anterior','Descrição Produto', 'Código GTIN',
                    'Unidade Comercial', 'Código NCM',
                    'Código CEST', 'Documento Fiscal.Número CNPJ Emitente (char)',
                    'Número CNPJ Destinatário (char)']]

file_1_new['Tipo'] = ['entrada_oprprp']*len(file_1_new)

file_1_new.head()

,Chave Acesso NFe,Data Emissão,Número Item,Código Produto ou Serviço,Código CFOP (04 Posições),Quantidade Comercial,Valor Produto ou Serviço,Valor ICMS,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base Cálculo ICMS ST Retido Operação Anterior,Descrição Produto,Código GTIN,Unidade Comercial,Código NCM,Código CEST,Documento Fiscal.Número CNPJ Emitente (char),Número CNPJ Destinatário (char),Tipo
0,35161003129126000159550020000014241120604712,02/10/2016,1,162164,1411,"1,0000","11,9",NaN,NaN,NaN,"18,55",Esc D Frescor 3d Piu Piu,7899360204851,UN,96032100,2005800.0,3129126000159,NaN,entrada_oprprp
1,35161003129126000159550020000014251120604973,02/10/2016,1,130393,1411,"1,0000","3,96",NaN,NaN,NaN,"5,8",Removedor Esm 80ml Farmax,7896902200494,UN,33043000,2800600.0,3129126000159,NaN,entrada_oprprp
2,35161003129126000159550020000014261120605020,02/10/2016,3,144667,1411,"3,0000","4,11",NaN,NaN,NaN,"5,67",Sb JeJ 90g Harmonize Erva Doce,7891010877989,UN,34011190,2802000.0,3129126000159,NaN,entrada_oprprp
3,35161003129126000159550020000014261120605020,02/10/2016,1,857441,1411,"3,0000","4,11",NaN,NaN,NaN,"5,67",Sb JeJ 90g Imagine Rosa Jasm,7891010690373,UN,34011190,2802000.0,3129126000159,NaN,entrada_oprprp
4,35161003129126000159550020000014261120605020,02/10/2016,2,857458,1411,"2,0000","2,74",NaN,NaN,NaN,"3,78",Sb JeJ 90g Relaxe Lavanda,7891010690380,UN,34011190,2802000.0,3129126000159,NaN,entrada_oprprp

In [6]:
# Leitura do arquivo de entradas- outras entradas
# (entradas de outros estados que não SP)

file_2 = pd.read_csv(f"C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\nfe_entrada_outras.txt", sep='\t', header=1, encoding = 'utf-8', encoding_errors='ignore')
file_2.head()

# Colunas a serem usadas:
# 'Chave Acesso NFe', 'Data Emissão','Número Item', 'Número CNPJ Emitente (char)',
# 'Número CNPJ Destinatário (char)', 'Código GTIN', 'Código NCM',
# 'Descrição Produto', 'Código CFOP (04 Posições)', 'Unidade Comercial',
# 'Valor Base Cálculo ICMS Substituição Tributária', 'Valor ICMS ST Retido Operação Anterior',
# 'Código Produto ou Serviço', 'Código CEST (char)'

,Chave Acesso Nota Fiscal,Chave Acesso NFe,Referencia Mês Emissão,Data Emissão,Indicador Situação Documento Fiscal,Indicador Tipo Documento Fiscal,Número CNPJ Emitente (char),Número CNPJ Destinatário (char),Número Item,Código NCM,...,Código Barra,Código CEST,Código CEST (char),Valor ICMS Operação,Valor ICMS Diferido,Valor Desconto Incondicionado,Valor Desconto Condicionado,Valor Outro,Valor Dedução,Quantidade Comercial
0,32.171.008.824.171.000.000.000.000.000.000.000...,32171008824171000570550010001283621111023105,201.710,23/10/2017,0,1,8824171000570,3129126000159,1,84145990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,0000"
1,32.171.008.824.171.000.000.000.000.000.000.000...,32171008824171000570550010001283621111023105,201.710,23/10/2017,0,1,8824171000570,3129126000159,2,84145990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,0000"
2,32.171.008.824.171.000.000.000.000.000.000.000...,32171008824171000570550010001283621111023105,201.710,23/10/2017,0,1,8824171000570,3129126000159,3,84145990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,0000"
3,32.180.928.268.233.000.000.000.000.000.000.000...,32180928268233000784550010001365811582318508,201.809,12/9/2018,0,1,28268233000784,3129126000159,1,85176259,...,NaN,2105600.0,2105600.0,NaN,NaN,NaN,NaN,NaN,NaN,"1,0000"
4,41.200.205.607.657.000.000.000.000.000.000.000...,41200205607657000135550030008811031006633449,202.002,10/2/2020,0,1,5607657000135,3129126000159,1,84705011,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,0000"

In [7]:
# Seleção das colunas necessárias do
# arquivo entradas-outras entradas

file_2_new = file_2.copy()
file_2_new = file_2_new[['Chave Acesso NFe', 'Data Emissão','Número Item','Código Produto ou Serviço',
                         'Código CFOP (04 Posições)','Quantidade Tributável','Valor Produto ou Serviço','Valor ICMS Operação',
                         'Valor ICMS Substituição Tributária', 'Valor Base Cálculo ICMS Substituição Tributária',
                         'Valor Base Cálculo ICMS ST Retido Operação Anterior','Descrição Produto', 'Código GTIN',
                         'Unidade Comercial','Código NCM','Código CEST (char)',
                         'Número CNPJ Emitente (char)','Número CNPJ Destinatário (char)']]

file_2_new['Tipo'] = ['entrada_outras']*len(file_2_new)
file_2_new.head()

,Chave Acesso NFe,Data Emissão,Número Item,Código Produto ou Serviço,Código CFOP (04 Posições),Quantidade Tributável,Valor Produto ou Serviço,Valor ICMS Operação,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base Cálculo ICMS ST Retido Operação Anterior,Descrição Produto,Código GTIN,Unidade Comercial,Código NCM,Código CEST (char),Número CNPJ Emitente (char),Número CNPJ Destinatário (char),Tipo
0,32171008824171000570550010001283621111023105,23/10/2017,1,4008,6.102,"2,0000",700,NaN,NaN,NaN,NaN,"CORTINA DE AR JCM 0,90 220/1 C/CONT",0000000004008,UN,84145990,NaN,8824171000570,3129126000159,entrada_outras
1,32171008824171000570550010001283621111023105,23/10/2017,2,4009,6.102,"2,0000",840,NaN,NaN,NaN,NaN,"CORTINA DE AR JCM 1,2 220/1 C/CONT",,UN,84145990,NaN,8824171000570,3129126000159,entrada_outras
2,32171008824171000570550010001283621111023105,23/10/2017,3,4010,6.102,"3,0000",1.620,NaN,NaN,NaN,NaN,"CORTINA DE AR JCM 1,5 220/1 C/CONT",,UN,84145990,NaN,8824171000570,3129126000159,entrada_outras
3,32180928268233000784550010001365811582318508,12/9/2018,1,FG-30E,6.923,"1,0000","1.155,64",NaN,NaN,NaN,NaN,"5 x GE RJ45 ports (Including 1 x WAN port, 4 x...",SEM GTIN,UN,85176259,2105600.0,28268233000784,3129126000159,entrada_outras
4,41200205607657000135550030008811031006633449,10/2/2020,1,802214,6.102,"1,0000",530,NaN,NaN,NaN,NaN,PIN-PAD IPP320 USB_PRP INGENICO PIN-PAD IPP320...,7898405530054,UN,84705011,NaN,5607657000135,3129126000159,entrada_outras

In [8]:
# Leitura do arquivo de entradas- entradas SP
# (entradas de SP)


file_3 = pd.read_csv(f"C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\nfe_entrada_sp.txt", sep='\t', header=1, encoding = 'utf-8')
file_3.head()

# Colunas a serem usadas:
# 'Chave Acesso NFe', 'Código CEST', 'Código CFOP (04 Posições)'
# 'Descrição Produto', 'Código Produto ou Serviço', 'Número Item', 'Data Emissão'
# 'Unidade Comercial', 'Número CNPJ Emitente', 'Número CNPJ Destinatário (char)'
# 'Código NCM', 'Código GTIN', 'Quantidade Comercial', 'Valor ICMS ST Retido Operação Anterior'
# 'Valor Produto ou Serviço', 'Valor ICMS Substituição Tributária'

C:\Users\vinic\AppData\Local\Temp\ipykernel_1000\3759211192.py:5: DtypeWarning: Columns (5,15,16,21,22,31,32,34,37) have mixed types. Specify dtype option on import or set low_memory=False.
  file_3 = pd.read_csv(f"C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\nfe_entrada_sp.txt", sep='\t', header=1, encoding = 'utf-8')

,Chave Acesso NFe,Código CEST,Código CEST (char),Código CFOP (04 Posições),Descrição Produto,Código Produto ou Serviço,Número Item,Data Emissão,Unidade Comercial,Número CNPJ Emitente,...,Valor ICMS,Valor ICMS Substituição Tributária,Valor ICMS Substituição Tributária Destino,Valor Total NFE do Produto,Valor Total Tributo,Valor Desconto Incondicional,Valor Desconto Condicional,Valor ICMS Substituto,Valor Frete,Valor Seguro
0,35161001206820000520550030030416241696113436,1300100.0,1300100.0,5405,MAXIDEX COL 5ML-REFERENCIA,0000574,7,27/10/2016,UN,1206820000520,...,NaN,NaN,NaN,"5,74",NaN,NaN,NaN,NaN,NaN,NaN
1,35161001206820000520550030030416241696113436,1300100.0,1300100.0,5405,*MAXITROL COL 5ML-REFERENCIA,0000590,8,27/10/2016,FRC,1206820000520,...,NaN,NaN,NaN,"11,85",NaN,NaN,NaN,NaN,NaN,NaN
2,35161001206820000520550030030416241696113436,1300100.0,1300100.0,5405,*MAXITROL POM 3.5G-REFERENCIA,0050636,9,27/10/2016,UN,1206820000520,...,NaN,NaN,NaN,"20,55",NaN,NaN,NaN,NaN,NaN,NaN
3,35161001206820000520550030030416241696113436,1300100.0,1300100.0,5405,UTROGESTAN 200MG CPS 1X14-REFERENCIA,0115199,20,27/10/2016,CX,1206820000520,...,NaN,NaN,NaN,"38,74",NaN,NaN,NaN,NaN,NaN,NaN
4,35161001206820000520550030030416241696113436,1300101.0,1300101.0,5405,PANTELMIN 500MG CPR 1X1-REFERENCIA,0104172,13,27/10/2016,CX,1206820000520,...,NaN,NaN,NaN,"8,69",NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Seleção das colunas necessárias do
# arquivo entradas-entradas SP

file_3_new = file_3.copy()
file_3_new = file_3_new[['Chave Acesso NFe', 'Data Emissão','Número Item','Código Produto ou Serviço',
                         'Código CFOP (04 Posições)','Quantidade Comercial', 'Valor Produto ou Serviço','Valor ICMS', 
                         'Valor ICMS Substituição Tributária','Valor Base Cálculo ICMS Substituição Tributária',
                         'Valor Base Cálculo ICMS ST Retido Operação Anterior',
                         'Descrição Produto','Código GTIN','Unidade Comercial','Código NCM',
                         'Código CEST','Número CNPJ Emitente', 'Número CNPJ Destinatário (char)']]

file_3_new['Tipo'] = ['entrada_sp']*len(file_3_new)

file_3_new.head()

,Chave Acesso NFe,Data Emissão,Número Item,Código Produto ou Serviço,Código CFOP (04 Posições),Quantidade Comercial,Valor Produto ou Serviço,Valor ICMS,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base Cálculo ICMS ST Retido Operação Anterior,Descrição Produto,Código GTIN,Unidade Comercial,Código NCM,Código CEST,Número CNPJ Emitente,Número CNPJ Destinatário (char),Tipo
0,35161001206820000520550030030416241696113436,27/10/2016,7,0000574,5405,"1,0000","6,08",NaN,NaN,NaN,"7,42",MAXIDEX COL 5ML-REFERENCIA,7896548111727,UN,30043210,1300100.0,1206820000520,3129126000159,entrada_sp
1,35161001206820000520550030030416241696113436,27/10/2016,8,0000590,5405,"1,0000","12,56",NaN,NaN,NaN,"15,36",*MAXITROL COL 5ML-REFERENCIA,7896548111987,FRC,30042079,1300100.0,1206820000520,3129126000159,entrada_sp
2,35161001206820000520550030030416241696113436,27/10/2016,9,0050636,5405,"1,0000","20,55",NaN,NaN,NaN,"26,58",*MAXITROL POM 3.5G-REFERENCIA,7896548198285,UN,30042079,1300100.0,1206820000520,3129126000159,entrada_sp
3,35161001206820000520550030030416241696113436,27/10/2016,20,0115199,5405,"1,0000","41,05",NaN,NaN,NaN,"50,17",UTROGESTAN 200MG CPS 1X14-REFERENCIA,7898948648148,CX,30043939,1300100.0,1206820000520,3129126000159,entrada_sp
4,35161001206820000520550030030416241696113436,27/10/2016,13,0104172,5405,"1,0000","9,22",NaN,NaN,NaN,"10,54",PANTELMIN 500MG CPR 1X1-REFERENCIA,7896212429028,CX,30049063,1300101.0,1206820000520,3129126000159,entrada_sp

In [10]:
# Leitura do arquivo de saídas-dfe

file_4 = pd.read_csv(f'C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\dfe.txt', encoding='utf-8', sep='\t', header=1)

file_4.head()

# Colunas a serem usadas:
# 'Descrição Produto', 'Código EAN', 'Código Produto', 'Chave CF-e', 'Unidade Comercial'
# 'Número Item', 'Código CFOP 04 Posições', 'Data Emissao', 'Quantidade Comercial'
# 'Valor Item'

C:\Users\vinic\AppData\Local\Temp\ipykernel_1000\110387083.py:3: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  file_4 = pd.read_csv(f'C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\dfe.txt', encoding='utf-8', sep='\t', header=1)

,Descrição Produto,Código CEST,Código EAN,Código Produto,Chave CF-e,Unidade Comercial,Número Item,Código CFOP 04 Posições,Informações Adicicionais,Num Cnpj Emit,Data Emissao,Valor Produtos,Valor Icms,Quantidade Comercial,Valor Item,Valor Unitário Comercialização,Valor Desconto,Valor Outro,Valor Rateio Desconto,Valor Rateio Acrescimo
0,0 - AVAMYS SPR NASAL 120,NaN,7.896016e+12,891853,35190503129126000159590006031130661738035562,UN,1,5405,NaN,03.129.126/0001-59,5/10/2019,"54,25",NaN,"1,0000","46,11","54,250","8,14",NaN,NaN,NaN
1,10011 - AAS MEDLEY INF 10'S,NaN,7.891058e+12,49916,35190503129126000159590005812820223414083570,UN,2,5405,NaN,03.129.126/0001-59,5/31/2019,"6,16",NaN,"1,0000","5,85","6,160","0,31",NaN,NaN,NaN
2,10011 - AAS MEDLEY INF 10'S,NaN,7.891058e+12,49916,35190903129126000159590005812820307000842750,UN,1,5405,NaN,03.129.126/0001-59,9/13/2019,"6,16",NaN,"1,0000","5,85","6,160","0,31",NaN,NaN,NaN
3,10011 - ABC SPRAY HERTZ,NaN,7.896332e+12,70540,35191203129126000159590006031131281841815091,UN,2,5405,NaN,03.129.126/0001-59,12/28/2019,"32,14",NaN,"1,0000","32,14","32,140",NaN,NaN,NaN,NaN
4,10011 - ABERALGINA 500MG 10M,NaN,7.894164e+12,223164,35191103129126000159590006031131161792323211,UN,4,5405,NaN,03.129.126/0001-59,11/16/2019,"6,49",NaN,"1,0000","0,98","6,490","5,51",NaN,NaN,NaN

In [11]:
file_4.columns

Index(['Descrição Produto', 'Código CEST', 'Código EAN', 'Código Produto',
       'Chave CF-e', 'Unidade Comercial', 'Número Item',
       'Código CFOP 04 Posições', 'Informações Adicicionais', 'Num Cnpj Emit',
       'Data Emissao', 'Valor Produtos', 'Valor Icms', 'Quantidade Comercial',
       'Valor Item', 'Valor Unitário Comercialização', 'Valor Desconto',
       'Valor Outro', 'Valor Rateio Desconto', 'Valor Rateio Acrescimo'],
      dtype='object')

In [12]:
# Seleção das colunas necessárias
# do arquivos saídas-dfe

file_4_new = file_4.copy()
file_4_new = file_4_new[['Chave CF-e', 'Data Emissao', 'Número Item',
                        'Código Produto', 'Código CFOP 04 Posições','Valor Icms',
                        'Quantidade Comercial', 'Valor Item','Descrição Produto','Código EAN',
                        'Unidade Comercial', 'Código CEST']]

file_4_new['Tipo'] = ['dfe']*len(file_4_new)

file_4_new.head()

,Chave CF-e,Data Emissao,Número Item,Código Produto,Código CFOP 04 Posições,Valor Icms,Quantidade Comercial,Valor Item,Descrição Produto,Código EAN,Unidade Comercial,Código CEST,Tipo
0,35190503129126000159590006031130661738035562,5/10/2019,1,891853,5405,NaN,"1,0000","46,11",0 - AVAMYS SPR NASAL 120,7.896016e+12,UN,NaN,dfe
1,35190503129126000159590005812820223414083570,5/31/2019,2,49916,5405,NaN,"1,0000","5,85",10011 - AAS MEDLEY INF 10'S,7.891058e+12,UN,NaN,dfe
2,35190903129126000159590005812820307000842750,9/13/2019,1,49916,5405,NaN,"1,0000","5,85",10011 - AAS MEDLEY INF 10'S,7.891058e+12,UN,NaN,dfe
3,35191203129126000159590006031131281841815091,12/28/2019,2,70540,5405,NaN,"1,0000","32,14",10011 - ABC SPRAY HERTZ,7.896332e+12,UN,NaN,dfe
4,35191103129126000159590006031131161792323211,11/16/2019,4,223164,5405,NaN,"1,0000","0,98",10011 - ABERALGINA 500MG 10M,7.894164e+12,UN,NaN,dfe

In [13]:
# Leitura do arquivo de saídas- nfe saídas

file_5 = pd.read_csv(f'C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\nfe_saidas.txt', encoding='utf-8', sep='\t', header=1)
file_5.head()

# Colunas a serem usadas:
# 'Data Emissão', 'Chave Acesso NFe', 'Código GTIN', 'Número Item'
# 'Código Produto ou Serviço', 'Descrição Produto', 'Código NCM'
# 'Código CFOP (04 Posições)', 'Unidade Comercial', 'Número CNPJ Destinatário (char)'
# 'Número CNPJ Emitente (char)', 'Quantidade Comercial', 'Valor Produto ou Serviço'

,Data Emissão,Chave Acesso NFe,Código CEST,Código GTIN,Código CEST (char),Número Item,Código Produto ou Serviço,Descrição Produto,Descrição Produto (original),Código NCM,...,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base Cálculo ICMS ST Retido Operação Anterior,Valor ICMS ST Retido Operação Anterior,Valor Total Tributo,Valor Total NFE do Produto,Valor Outras Despesas Acessórias,Valor Dedução,Valor Desconto Incondicional,Valor Desconto Condicional
0,01/10/2016,35161003129126000159550020000014191120593150,2802000.0,,2802000.0,1,159137,Kit Sb Le Blue Vegetal 4un,Kit Sb Le Blue Vegetal 4un,34011190,...,NaN,NaN,"16,55","0,82",NaN,12,NaN,NaN,NaN,NaN
1,01/10/2016,35161003129126000159550020000014191120593150,2802000.0,,2802000.0,2,159129,Kit Sb Le Blue Vegetal Esf 4un,Kit Sb Le Blue Vegetal Esf 4un,34011190,...,NaN,NaN,"17,93","0,89",NaN,13,NaN,NaN,NaN,NaN
2,01/10/2016,35161003129126000159550020000014201120593169,2002300.0,,2002300.0,2,143917,Kit Dental Clean Viagem+Necess,Kit Dental Clean Viagem+Necess,33061000,...,NaN,NaN,"14,76","0,52",NaN,"10,38",NaN,NaN,NaN,NaN
3,01/10/2016,35161003129126000159550020000014201120593169,2801600.0,,2801600.0,1,121723,Des Nivea Aer M Stress Prot,Des Nivea Aer M Stress Prot,33072010,...,NaN,NaN,"11,3","0,57",NaN,"8,12",NaN,NaN,NaN,NaN
4,01/10/2016,35161003129126000159550020000014211120593182,302200.0,,302200.0,2,74666,I9 500ml Tangerina,I9 500ml Tangerina,22029000,...,NaN,NaN,"19,11","0,98",NaN,"13,65",NaN,NaN,NaN,NaN

In [14]:
# Seleção das colunas necessárias
# do arquivo saídas - nfe saídas

file_5_new = file_5.copy()
file_5_new = file_5_new[['Chave Acesso NFe', 'Data Emissão', 'Número Item',
                        'Código Produto ou Serviço', 'Código CFOP (04 Posições)',
                        'Quantidade Comercial', 'Valor Produto ou Serviço','Valor ICMS',
                        'Descrição Produto','Código GTIN', 'Unidade Comercial',
                        'Código NCM','Código CEST', 'Número CNPJ Emitente (char)',
                        'Número CNPJ Destinatário (char)']]

file_5_new['Tipo'] = ['saida_nfe']*len(file_5_new)

file_5_new.head()

,Chave Acesso NFe,Data Emissão,Número Item,Código Produto ou Serviço,Código CFOP (04 Posições),Quantidade Comercial,Valor Produto ou Serviço,Valor ICMS,Descrição Produto,Código GTIN,Unidade Comercial,Código NCM,Código CEST,Número CNPJ Emitente (char),Número CNPJ Destinatário (char),Tipo
0,35161003129126000159550020000014191120593150,01/10/2016,1,159137,5927,"2,0000",12,NaN,Kit Sb Le Blue Vegetal 4un,,UN,34011190,2802000.0,3129126000159,3129126000159,saida_nfe
1,35161003129126000159550020000014191120593150,01/10/2016,2,159129,5927,"2,0000",13,NaN,Kit Sb Le Blue Vegetal Esf 4un,,UN,34011190,2802000.0,3129126000159,3129126000159,saida_nfe
2,35161003129126000159550020000014201120593169,01/10/2016,2,143917,5927,"1,0000","10,38",NaN,Kit Dental Clean Viagem+Necess,,UN,33061000,2002300.0,3129126000159,3129126000159,saida_nfe
3,35161003129126000159550020000014201120593169,01/10/2016,1,121723,5927,"1,0000","8,12",NaN,Des Nivea Aer M Stress Prot,,UN,33072010,2801600.0,3129126000159,3129126000159,saida_nfe
4,35161003129126000159550020000014211120593182,01/10/2016,2,74666,5927,"5,0000","13,65",NaN,I9 500ml Tangerina,,UN,22029000,302200.0,3129126000159,3129126000159,saida_nfe

In [15]:
# Renomeação das colunas do dataframe
# de entradas

file_1_new.rename(
    columns={'Número CNPJ Destinatário (char)':'Número CNPJ Destinatário',
            'Documento Fiscal.Número CNPJ Emitente (char)':'Número CNPJ Emitente',
            'Valor ICMS': 'Valor ICMS Operação'}, inplace=True)

file_1_new['Data Emissão'] = pd.to_datetime(file_1_new['Data Emissão'], format='%d/%m/%Y')
file_1_new.columns

Index(['Chave Acesso NFe', 'Data Emissão', 'Número Item',
       'Código Produto ou Serviço', 'Código CFOP (04 Posições)',
       'Quantidade Comercial', 'Valor Produto ou Serviço',
       'Valor ICMS Operação', 'Valor ICMS Substituição Tributária',
       'Valor Base Cálculo ICMS Substituição Tributária',
       'Valor Base Cálculo ICMS ST Retido Operação Anterior',
       'Descrição Produto', 'Código GTIN', 'Unidade Comercial', 'Código NCM',
       'Código CEST', 'Número CNPJ Emitente', 'Número CNPJ Destinatário',
       'Tipo'],
      dtype='object')

In [16]:
file_2_new.rename(
    columns={'Quantidade Tributável':'Quantidade Comercial',
            'Código CEST (char)':'Código CEST',
             'Valor ICMS': 'Valor ICMS Operação',
            'Número CNPJ Emitente (char)':'Número CNPJ Emitente',
            'Número CNPJ Destinatário (char)':'Número CNPJ Destinatário'}, inplace=True)

file_2_new['Data Emissão'] = pd.to_datetime(file_2_new['Data Emissão'], format='%d/%m/%Y')
file_2_new.columns

Index(['Chave Acesso NFe', 'Data Emissão', 'Número Item',
       'Código Produto ou Serviço', 'Código CFOP (04 Posições)',
       'Quantidade Comercial', 'Valor Produto ou Serviço',
       'Valor ICMS Operação', 'Valor ICMS Substituição Tributária',
       'Valor Base Cálculo ICMS Substituição Tributária',
       'Valor Base Cálculo ICMS ST Retido Operação Anterior',
       'Descrição Produto', 'Código GTIN', 'Unidade Comercial', 'Código NCM',
       'Código CEST', 'Número CNPJ Emitente', 'Número CNPJ Destinatário',
       'Tipo'],
      dtype='object')

In [17]:
file_3_new.rename(
    columns={'Número CNPJ Destinatário (char)':'Número CNPJ Destinatário',
            'Valor ICMS': 'Valor ICMS Operação'}, inplace=True)

file_3_new['Data Emissão'] = pd.to_datetime(file_3_new['Data Emissão'], format='%d/%m/%Y')
file_3_new.columns

Index(['Chave Acesso NFe', 'Data Emissão', 'Número Item',
       'Código Produto ou Serviço', 'Código CFOP (04 Posições)',
       'Quantidade Comercial', 'Valor Produto ou Serviço',
       'Valor ICMS Operação', 'Valor ICMS Substituição Tributária',
       'Valor Base Cálculo ICMS Substituição Tributária',
       'Valor Base Cálculo ICMS ST Retido Operação Anterior',
       'Descrição Produto', 'Código GTIN', 'Unidade Comercial', 'Código NCM',
       'Código CEST', 'Número CNPJ Emitente', 'Número CNPJ Destinatário',
       'Tipo'],
      dtype='object')

In [18]:
file_4_new.rename(
    columns={'Chave CF-e':'Chave Acesso NFe',
            'Código Produto':'Código Produto ou Serviço',
            'Data Emissao':'Data Emissão',
             'Valor Icms': 'Valor ICMS Operação',
            'Código CFOP 04 Posições':'Código CFOP (04 Posições)',
            'Valor Item':'Valor Produto ou Serviço',
            'Código EAN': 'Código GTIN'}, inplace=True)

file_4_new.columns

Index(['Chave Acesso NFe', 'Data Emissão', 'Número Item',
       'Código Produto ou Serviço', 'Código CFOP (04 Posições)',
       'Valor ICMS Operação', 'Quantidade Comercial',
       'Valor Produto ou Serviço', 'Descrição Produto', 'Código GTIN',
       'Unidade Comercial', 'Código CEST', 'Tipo'],
      dtype='object')

In [19]:
file_4_new['Valor ICMS Substituição Tributária'] = np.nan
file_4_new['Valor Base Cálculo ICMS Substituição Tributária'] = np.nan
file_4_new['Valor Base Cálculo ICMS ST Retido Operação Anterior'] = np.nan
file_4_new['Código NCM'] = np.nan
file_4_new['Número CNPJ Emitente'] = np.nan
file_4_new['Número CNPJ Destinatário'] = np.nan
file_4_new['Data Emissão'] = pd.to_datetime(file_4_new['Data Emissão'], format='%m/%d/%Y')
file_4_new.head()

,Chave Acesso NFe,Data Emissão,Número Item,Código Produto ou Serviço,Código CFOP (04 Posições),Valor ICMS Operação,Quantidade Comercial,Valor Produto ou Serviço,Descrição Produto,Código GTIN,Unidade Comercial,Código CEST,Tipo,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base Cálculo ICMS ST Retido Operação Anterior,Código NCM,Número CNPJ Emitente,Número CNPJ Destinatário
0,35190503129126000159590006031130661738035562,2019-05-10,1,891853,5405,NaN,"1,0000","46,11",0 - AVAMYS SPR NASAL 120,7.896016e+12,UN,NaN,dfe,NaN,NaN,NaN,NaN,NaN,NaN
1,35190503129126000159590005812820223414083570,2019-05-31,2,49916,5405,NaN,"1,0000","5,85",10011 - AAS MEDLEY INF 10'S,7.891058e+12,UN,NaN,dfe,NaN,NaN,NaN,NaN,NaN,NaN
2,35190903129126000159590005812820307000842750,2019-09-13,1,49916,5405,NaN,"1,0000","5,85",10011 - AAS MEDLEY INF 10'S,7.891058e+12,UN,NaN,dfe,NaN,NaN,NaN,NaN,NaN,NaN
3,35191203129126000159590006031131281841815091,2019-12-28,2,70540,5405,NaN,"1,0000","32,14",10011 - ABC SPRAY HERTZ,7.896332e+12,UN,NaN,dfe,NaN,NaN,NaN,NaN,NaN,NaN
4,35191103129126000159590006031131161792323211,2019-11-16,4,223164,5405,NaN,"1,0000","0,98",10011 - ABERALGINA 500MG 10M,7.894164e+12,UN,NaN,dfe,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
file_5_new.rename(
    columns={'Número CNPJ Emitente (char)':'Número CNPJ Emitente',
             'Valor ICMS': 'Valor ICMS Operação',
            'Número CNPJ Destinatário (char)':'Número CNPJ Destinatário'}, inplace=True)

file_5_new.columns

Index(['Chave Acesso NFe', 'Data Emissão', 'Número Item',
       'Código Produto ou Serviço', 'Código CFOP (04 Posições)',
       'Quantidade Comercial', 'Valor Produto ou Serviço',
       'Valor ICMS Operação', 'Descrição Produto', 'Código GTIN',
       'Unidade Comercial', 'Código NCM', 'Código CEST',
       'Número CNPJ Emitente', 'Número CNPJ Destinatário', 'Tipo'],
      dtype='object')

In [21]:
file_5_new['Valor ICMS Substituição Tributária'] = np.nan
file_5_new['Valor Base Cálculo ICMS Substituição Tributária'] = np.nan
file_5_new['Valor Base Cálculo ICMS ST Retido Operação Anterior'] = np.nan
file_5_new['Data Emissão'] = pd.to_datetime(file_5_new['Data Emissão'], format='%d/%m/%Y')

file_5_new.head()

,Chave Acesso NFe,Data Emissão,Número Item,Código Produto ou Serviço,Código CFOP (04 Posições),Quantidade Comercial,Valor Produto ou Serviço,Valor ICMS Operação,Descrição Produto,Código GTIN,Unidade Comercial,Código NCM,Código CEST,Número CNPJ Emitente,Número CNPJ Destinatário,Tipo,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base Cálculo ICMS ST Retido Operação Anterior
0,35161003129126000159550020000014191120593150,2016-10-01,1,159137,5927,"2,0000",12,NaN,Kit Sb Le Blue Vegetal 4un,,UN,34011190,2802000.0,3129126000159,3129126000159,saida_nfe,NaN,NaN,NaN
1,35161003129126000159550020000014191120593150,2016-10-01,2,159129,5927,"2,0000",13,NaN,Kit Sb Le Blue Vegetal Esf 4un,,UN,34011190,2802000.0,3129126000159,3129126000159,saida_nfe,NaN,NaN,NaN
2,35161003129126000159550020000014201120593169,2016-10-01,2,143917,5927,"1,0000","10,38",NaN,Kit Dental Clean Viagem+Necess,,UN,33061000,2002300.0,3129126000159,3129126000159,saida_nfe,NaN,NaN,NaN
3,35161003129126000159550020000014201120593169,2016-10-01,1,121723,5927,"1,0000","8,12",NaN,Des Nivea Aer M Stress Prot,,UN,33072010,2801600.0,3129126000159,3129126000159,saida_nfe,NaN,NaN,NaN
4,35161003129126000159550020000014211120593182,2016-10-01,2,74666,5927,"5,0000","13,65",NaN,I9 500ml Tangerina,,UN,22029000,302200.0,3129126000159,3129126000159,saida_nfe,NaN,NaN,NaN

In [22]:
file_1_new = file_1_new.astype(str)
file_2_new = file_2_new.astype(str)
file_3_new = file_3_new.astype(str)
file_4_new = file_4_new.astype(str)
file_5_new = file_5_new.astype(str)

In [23]:
df_final = pd.concat([file_1_new, file_2_new, file_3_new, file_4_new, file_5_new])

if periodo == 0:
    df_final = df_final[df_final['Data Emissão'] < '2018-05-01']
    
elif periodo == 1:
    df_final = df_final[(df_final['Data Emissão'] >= '2018-05-01')&(df_final['Data Emissão'] < '2019-10-01')]
    
elif periodo == 2:
    df_final = df_final[df_final['Data Emissão'] >= '2019-10-01']
df_final

,Chave Acesso NFe,Data Emissão,Número Item,Código Produto ou Serviço,Código CFOP (04 Posições),Quantidade Comercial,Valor Produto ou Serviço,Valor ICMS Operação,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base Cálculo ICMS ST Retido Operação Anterior,Descrição Produto,Código GTIN,Unidade Comercial,Código NCM,Código CEST,Número CNPJ Emitente,Número CNPJ Destinatário,Tipo
1013,35191003129126000159550020000027291157936550,2019-10-01,1,94771,1411,"1,0000","13,81",nan,nan,nan,nan,Nimesulida Novaq 100mg 12S,SEM GTIN,UN,30049079,1300200.0,3129126000159,0.0,entrada_oprprp
1014,35191003129126000159550020000027301158021920,2019-10-02,1,148098,1411,"1,0000","27,99",nan,nan,nan,nan,Kit Concare Manicure,SEM GTIN,UN,82142000,2802600.0,3129126000159,0.0,entrada_oprprp
1015,35191003129126000159550020000027311158028019,2019-10-02,1,155283,1411,"1,0000","22,1",nan,nan,nan,nan,Creme Prev Assadur 45g Le Blue,SEM GTIN,UN,33049910,2800800.0,3129126000159,0.0,entrada_oprprp
1016,35191003129126000159550020000027311158028019,2019-10-02,2,155283,1411,"1,0000","22,1",nan,nan,nan,nan,Creme Prev Assadur 45g Le Blue,SEM GTIN,UN,33049910,2800800.0,3129126000159,0.0,entrada_oprprp
1017,35191003129126000159550020000027321158122292,2019-10-03,1,78550,1411,"1,0000","20,08",nan,nan,nan,nan,Ibuprofeno Prati 600mg 20S,SEM GTIN,UN,30049029,1300200.0,3129126000159,0.0,entrada_oprprp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2947,35201203129126000159550030000000811873914353,2020-12-26,10,167734,5927,"2,0000","12,08",nan,nan,nan,nan,LEITE ENSURE 220ML PROTEIN BAU,7891158102523,UN,21069090,nan,3129126000159,3129126000159,saida_nfe
2948,35201203129126000159550030000000811873914353,2020-12-26,14,211011,5927,"8,0000","1,72",nan,nan,nan,nan,FINI BEM ESTAR ACAI 18G,7898591457913,UN,17049020,nan,3129126000159,3129126000159,saida_nfe
2949,35201203129126000159550030000000811873914353,2020-12-26,11,170316,5927,"2,0000","10,23",nan,nan,nan,nan,VITACON GOLD 30S,7898623351738,UN,21069030,nan,3129126000159,3129126000159,saida_nfe
2950,35201203129126000159550030000000821875880437,2020-12-26,1,201905,5927,"2,0000","2,16",nan,nan,nan,nan,FR PLENIT ACT MULHER P/M 8UN,7896007550043,UN,96190000,2004800.0,3129126000159,3129126000159,saida_nfe
2951,35201203129126000159550030000000851871292915,2020-12-28,1,239772,5927,"3,0000","55,62",nan,nan,nan,nan,ALCOOL GEL CONCARE C FLOW 400G,7898623356252,UN,22072019,1101000.0,3129126000159,3129126000159,saida_nfe

In [24]:
df_final.to_csv(f'C:\\Bots\\Bot_transmissao\\Geracao CAT\\Loja_{loja}\\loja_{loja}_tabela_1_p{periodo}.csv', encoding='utf-8')